export const MessData = [
  {
    Day: 'Monday',
    BreakFast: [
      'IDLY, VADA (2 Nos - 80 gms each)',
      'SAMBAR',
      'COCONUT CHUTNEY',
      'SPROUTS (50 gms each)',
      'BREAD TOASTED WITH BUTTER AND JAM',
      'TEA',
      'COFFEE',
      'MILK',
      '1 BOILED EGG/OMELET (OR) BANANA(FOR THOSE WHO DO NOT EAT EGG)',
    ],

    Lunch: [
      'RICE',
      'PHULKA/CHAPATI',
      'GHEE',
      'MIX VEG CURRY',
      'DAL ARHAR',
      'BHINDI DRY',
      'SAMBAR',
      'TOMATO RICE',
      'CURD',
      'RAITA',
      'PAPAD/ FRYUMS',
      'PICKLE',
      'SALT',
      'SUGAR',
      'VEG SALAD',
      'LEMON SLICES + BUTTERMILK',
    ],

    Snacks: [
      'TEA/COFFEE/MILK',
      'VEG CUTLET (2 PIECES)',
      'KETCHUP',
      'GREEN CHUTNEY',
      'SEASONAL FRUIT',
    ],

    Dinner: [
      'RICE',
      'PHULKA/CHAPATI',
      'GHEE',
      'RAJMA GRAVY',
      'DAL PALAK',
      'LAUKI CHANA TOMATO',
      'GARLIC RASAM',
      'CURD',
      'PAPAD/ FRYUMS',
      'PICKLE',
      'SALT',
      'SUGAR',
      'VEG SALAD',
      'LEMON SLICES',
      'ICE CREAM (2 SCOOPS PER PERSON)',
    ],
  },
  {
    Day: 'Tuesday',
    BreakFast: [
      'IDLY, VADA (2 Nos - 80 gms each)',
      'SAMBAR',
      'COCONUT CHUTNEY',
      'SPROUTS (50 gms each)',
      'BREAD TOASTED WITH BUTTER AND JAM',
      'TEA',
      'COFFEE',
      'MILK',
      '1 BOILED EGG/OMELET (OR) BANANA(FOR THOSE WHO DO NOT EAT EGG)',
    ],

    Lunch: [
      'RICE',
      'PHULKA/CHAPATI',
      'GHEE',
      'MIX VEG CURRY',
      'DAL ARHAR',
      'BHINDI DRY',
      'SAMBAR',
      'TOMATO RICE',
      'CURD',
      'RAITA',
      'PAPAD/ FRYUMS',
      'PICKLE',
      'SALT',
      'SUGAR',
      'VEG SALAD',
      'LEMON SLICES + BUTTERMILK',
    ],

    Snacks: [
      'TEA/COFFEE/MILK',
      'VEG CUTLET (2 PIECES)',
      'KETCHUP',
      'GREEN CHUTNEY',
      'SEASONAL FRUIT',
    ],

    Dinner: [
      'RICE',
      'PHULKA/CHAPATI',
      'GHEE',
      'RAJMA GRAVY',
      'DAL PALAK',
      'LAUKI CHANA TOMATO',
      'GARLIC RASAM',
      'CURD',
      'PAPAD/ FRYUMS',
      'PICKLE',
      'SALT',
      'SUGAR',
      'VEG SALAD',
      'LEMON SLICES',
      'ICE CREAM (2 SCOOPS PER PERSON)',
    ],
  },
  {
    Day: 'Wednesday',
    BreakFast: [
      'IDLY, VADA (2 Nos - 80 gms each)',
      'SAMBAR',
      'COCONUT CHUTNEY',
      'SPROUTS (50 gms each)',
      'BREAD TOASTED WITH BUTTER AND JAM',
      'TEA',
      'COFFEE',
      'MILK',
      '1 BOILED EGG/OMELET (OR) BANANA(FOR THOSE WHO DO NOT EAT EGG)',
    ],

    Lunch: [
      'RICE',
      'PHULKA/CHAPATI',
      'GHEE',
      'MIX VEG CURRY',
      'DAL ARHAR',
      'BHINDI DRY',
      'SAMBAR',
      'TOMATO RICE',
      'CURD',
      'RAITA',
      'PAPAD/ FRYUMS',
      'PICKLE',
      'SALT',
      'SUGAR',
      'VEG SALAD',
      'LEMON SLICES + BUTTERMILK',
    ],

    Snacks: [
      'TEA/COFFEE/MILK',
      'VEG CUTLET (2 PIECES)',
      'KETCHUP',
      'GREEN CHUTNEY',
      'SEASONAL FRUIT',
    ],

    Dinner: [
      'RICE',
      'PHULKA/CHAPATI',
      'GHEE',
      'RAJMA GRAVY',
      'DAL PALAK',
      'LAUKI CHANA TOMATO',
      'GARLIC RASAM',
      'CURD',
      'PAPAD/ FRYUMS',
      'PICKLE',
      'SALT',
      'SUGAR',
      'VEG SALAD',
      'LEMON SLICES',
      'ICE CREAM (2 SCOOPS PER PERSON)',
    ],
  },
  {
    Day: 'Thursday',
    BreakFast: [
      'IDLY, VADA (2 Nos - 80 gms each)',
      'SAMBAR',
      'COCONUT CHUTNEY',
      'SPROUTS (50 gms each)',
      'BREAD TOASTED WITH BUTTER AND JAM',
      'TEA',
      'COFFEE',
      'MILK',
      '1 BOILED EGG/OMELET (OR) BANANA(FOR THOSE WHO DO NOT EAT EGG)',
    ],

    Lunch: [
      'RICE',
      'PHULKA/CHAPATI',
      'GHEE',
      'MIX VEG CURRY',
      'DAL ARHAR',
      'BHINDI DRY',
      'SAMBAR',
      'TOMATO RICE',
      'CURD',
      'RAITA',
      'PAPAD/ FRYUMS',
      'PICKLE',
      'SALT',
      'SUGAR',
      'VEG SALAD',
      'LEMON SLICES + BUTTERMILK',
    ],

    Snacks: [
      'TEA/COFFEE/MILK',
      'VEG CUTLET (2 PIECES)',
      'KETCHUP',
      'GREEN CHUTNEY',
      'SEASONAL FRUIT',
    ],

    Dinner: [
      'RICE',
      'PHULKA/CHAPATI',
      'GHEE',
      'RAJMA GRAVY',
      'DAL PALAK',
      'LAUKI CHANA TOMATO',
      'GARLIC RASAM',
      'CURD',
      'PAPAD/ FRYUMS',
      'PICKLE',
      'SALT',
      'SUGAR',
      'VEG SALAD',
      'LEMON SLICES',
      'ICE CREAM (2 SCOOPS PER PERSON)',
    ],
  },
  {
    Day: 'Friday',
    BreakFast: [
      'IDLY, VADA (2 Nos - 80 gms each)',
      'SAMBAR',
      'COCONUT CHUTNEY',
      'SPROUTS (50 gms each)',
      'BREAD TOASTED WITH BUTTER AND JAM',
      'TEA',
      'COFFEE',
      'MILK',
      '1 BOILED EGG/OMELET (OR) BANANA(FOR THOSE WHO DO NOT EAT EGG)',
    ],

    Lunch: [
      'RICE',
      'PHULKA/CHAPATI',
      'GHEE',
      'MIX VEG CURRY',
      'DAL ARHAR',
      'BHINDI DRY',
      'SAMBAR',
      'TOMATO RICE',
      'CURD',
      'RAITA',
      'PAPAD/ FRYUMS',
      'PICKLE',
      'SALT',
      'SUGAR',
      'VEG SALAD',
      'LEMON SLICES + BUTTERMILK',
    ],

    Snacks: [
      'TEA/COFFEE/MILK',
      'VEG CUTLET (2 PIECES)',
      'KETCHUP',
      'GREEN CHUTNEY',
      'SEASONAL FRUIT',
    ],

    Dinner: [
      'RICE',
      'PHULKA/CHAPATI',
      'GHEE',
      'RAJMA GRAVY',
      'DAL PALAK',
      'LAUKI CHANA TOMATO',
      'GARLIC RASAM',
      'CURD',
      'PAPAD/ FRYUMS',
      'PICKLE',
      'SALT',
      'SUGAR',
      'VEG SALAD',
      'LEMON SLICES',
      'ICE CREAM (2 SCOOPS PER PERSON)',
    ],
  },
  {
    Day: 'Saturday',
    BreakFast: [
      'IDLY, VADA (2 Nos - 80 gms each)',
      'SAMBAR',
      'COCONUT CHUTNEY',
      'SPROUTS (50 gms each)',
      'BREAD TOASTED WITH BUTTER AND JAM',
      'TEA',
      'COFFEE',
      'MILK',
      '1 BOILED EGG/OMELET (OR) BANANA(FOR THOSE WHO DO NOT EAT EGG)',
    ],

    Lunch: [
      'RICE',
      'PHULKA/CHAPATI',
      'GHEE',
      'MIX VEG CURRY',
      'DAL ARHAR',
      'BHINDI DRY',
      'SAMBAR',
      'TOMATO RICE',
      'CURD',
      'RAITA',
      'PAPAD/ FRYUMS',
      'PICKLE',
      'SALT',
      'SUGAR',
      'VEG SALAD',
      'LEMON SLICES + BUTTERMILK',
    ],

    Snacks: [
      'TEA/COFFEE/MILK',
      'VEG CUTLET (2 PIECES)',
      'KETCHUP',
      'GREEN CHUTNEY',
      'SEASONAL FRUIT',
    ],

    Dinner: [
      'RICE',
      'PHULKA/CHAPATI',
      'GHEE',
      'RAJMA GRAVY',
      'DAL PALAK',
      'LAUKI CHANA TOMATO',
      'GARLIC RASAM',
      'CURD',
      'PAPAD/ FRYUMS',
      'PICKLE',
      'SALT',
      'SUGAR',
      'VEG SALAD',
      'LEMON SLICES',
      'ICE CREAM (2 SCOOPS PER PERSON)',
    ],
  },
  {
    Day: 'Sunday',
    BreakFast: [
      'IDLY, VADA (2 Nos - 80 gms each)',
      'SAMBAR',
      'COCONUT CHUTNEY',
      'SPROUTS (50 gms each)',
      'BREAD TOASTED WITH BUTTER AND JAM',
      'TEA',
      'COFFEE',
      'MILK',
      '1 BOILED EGG/OMELET (OR) BANANA(FOR THOSE WHO DO NOT EAT EGG)',
    ],

    Lunch: [
      'RICE',
      'PHULKA/CHAPATI',
      'GHEE',
      'MIX VEG CURRY',
      'DAL ARHAR',
      'BHINDI DRY',
      'SAMBAR',
      'TOMATO RICE',
      'CURD',
      'RAITA',
      'PAPAD/ FRYUMS',
      'PICKLE',
      'SALT',
      'SUGAR',
      'VEG SALAD',
      'LEMON SLICES + BUTTERMILK',
    ],

    Snacks: [
      'TEA/COFFEE/MILK',
      'VEG CUTLET (2 PIECES)',
      'KETCHUP',
      'GREEN CHUTNEY',
      'SEASONAL FRUIT',
    ],

    Dinner: [
      'RICE',
      'PHULKA/CHAPATI',
      'GHEE',
      'RAJMA GRAVY',
      'DAL PALAK',
      'LAUKI CHANA TOMATO',
      'GARLIC RASAM',
      'CURD',
      'PAPAD/ FRYUMS',
      'PICKLE',
      'SALT',
      'SUGAR',
      'VEG SALAD',
      'LEMON SLICES',
      'ICE CREAM (2 SCOOPS PER PERSON)',
    ],
  },
];

export const MessTimings = [
  {
    typeFood: 'Breakfast',

    Weekdays: '7:00 - 9:10 AM',
    Weekends: '7:30 - 9:30 AM',
  },
  {
    typeFood: 'Lunch',
    Weekdays: '12:00 - 2:00 PM',
    Weekends: '12:30 - 2:30 PM',
  },
  {
    typeFood: 'Snacks',
    Weekdays: '04:30 - 6:00 PM',
    Weekends: '04:30 - 6:00 PM',
  },
  {
    typeFood: 'Dinner',
    Weekdays: '7:00 - 9:00 PM',
    Weekends: '7:30 - 9:30 PM',
  },
];
